### ISSUE TITLE
In ActuatorModel cannot find instance: TurbineFastDisk

### ISSUE THREAD

**Issue by justhawk98** [rybchuk/amr-wind-tutorial#2]
Hi, I've been working through your tutorial and completed the spinup and precursor simulations without any problems. I'm now working on the turbine portion but when I start AMR-Wind, I get the following error:

Initializing I/O manager
ActuatorModel 4
 - UniformCtDisk
 - FixedWingLine
 - JoukowskyDisk
 - FlatPlateLine
terminate called after throwing an instance of 'std::runtime_error'
  what():  In ActuatorModel cannot find instance: TurbineFastDisk
[m12-2-8:02127] *** Process received signal ***
[m12-2-8:02127] Signal: Aborted (6)

So I see the issue is with the TurbineFastDisk model. I even tried changing the actuator type to TurbineFastLine for all three of the turbines and got the same error but saying " In ActuatorModel cannot find instance: TurbineFastLine". I have made sure to do the proper setup steps. I ran the python script for creating avg_theta.dat and added it to the directory. I also made sure to change the addresses for PerfFileName and set CompServo = 0 in the .fst files (just wanted to get something running and didn't want to worry about ROSCO). 

I've attached a .tar.gz file of the input file and the two error messages I got. Any tips would be appreciated, thanks!
[turbine.tar.gz](https://github.com/rybchuk/amr-wind-tutorial/files/14618118/turbine.tar.gz)

**Comment by rybchuk** [comment]
Ooh interesting, I haven't seen this error before. I haven't seen  To be certain, did you [compile](https://github.com/rybchuk/amr-wind-tutorial/blob/main/01_compiling.md) AMR-Wind with the OpenFAST flag? It would look something like
```
quick-create-dev -d ${SPACKMANDIR}/spack-july2023 -s openfast@master%gcc@11.2.0 amr-wind@main+openfast+hdf5%gcc@11.2.0
```

@AsimUdel, just to confirm - in the issue you recently posted to the main repo, your code ran beyond this point in the log file, right?

```
...
Initializing boundary conditions for velocity_mean
Creating FieldTimeAverage instance: ReAveraging
Initializing boundary conditions for velocity_stress
Initializing boundary conditions for velocity_reynolds_stress
Creating FieldTimeAverage instance: ReynoldsStress
Initializing I/O manager
ActuatorModel 4
 - UniformCtDisk
 - FixedWingLine
 - JoukowskyDisk
 - FlatPlateLine
terminate called after throwing an instance of 'std::runtime_error'
  what():  In ActuatorModel cannot find instance: TurbineFastLine
...
```

**Comment by AsimUdel** [comment]
@Alex, thanks for asking. I have not run the simulation (https://github.com/rybchuk/amr-wind-tutorial/blob/main/03_turbines.md), will try soon and get back to you.

**Comment by justhawk98** [comment]
Ah, I bet the OpenFAST flag is the problem. I didn't handle the installation but I doubt it was included. I'll get in touch with my super computer team and let you know. Any other compilation/installation tips before we recompile? Thanks!

**Comment by rybchuk** [comment]
> Ah, I bet the OpenFAST flag is the problem. I didn't handle the installation but I doubt it was included. I'll get in touch with my super computer team and let you know. Any other compilation/installation tips before we recompile? Thanks!

Good to hear! 
* Make sure that ROSCO, OpenFAST, and AMR-Wind are all using the same compiler. 
* I recommend with the `+hdf5` flag for AMR-Wind
* AMR-Wind supports OpenFAST up through version 3.4.1 
* Take notes as you compile on what commands you use :) If/when you need to recompile in the future, this will help a lot

**Comment by justhawk98** [comment]
We recompiled with the OpenFAST flag and I no longer got that error. There were a few others I had to work through after that but I finally got it running. Thanks!
