### ISSUE TITLE
plotting files in ParaView

### ISSUE THREAD

**Issue by AsimUdel** [rybchuk/amr-wind-tutorial#3]
Hi @rybchuk ,
Just a quick question, here (https://github.com/rybchuk/amr-wind-tutorial/blob/main/03_turbines.md) when you plotted files in ParaView to first see the mesh and then the time-averaged x-component of velocity, did you plot (plt files or the (sampling or abl statistics files))? I have tried to plot these files in ParaView but the file extension did not support ParaView.

**Comment by rybchuk** [comment]
Hi Asim,

I was plotting the `plt#####/` files. These files are based off the [AMReX plotfiles](https://amrex-codes.github.io/amrex/docs_html/IO.html) data format (which itself is built off the BoxLib data format), and they have some docs on how to visualize plotfiles [here](https://amrex-codes.github.io/amrex/docs_html/Visualization_Chapter.html).

To open a plotfile, I hit OK in the below image:
![image](https://github.com/rybchuk/amr-wind-tutorial/assets/8021012/4e97e2b5-11d4-4775-acf1-b7d638ead93c)

and then I open with the `AMReX/BoxLib Grid Reader`:
![image](https://github.com/rybchuk/amr-wind-tutorial/assets/8021012/38095bb2-ec99-4b42-bb4d-99b65fe3d3aa)

and that pulls the data into Paraview:
![image](https://github.com/rybchuk/amr-wind-tutorial/assets/8021012/a045a829-02ca-4b88-b92c-04e6ce10c69e)


Are you getting the `AMReX/BoxLib Grid Reader` prompt? I would guess that's where the error is happening. I'm running this in Paraview 5.10.1 by the way.

**Comment by AsimUdel** [comment]
Thank you so much, you were on point, I was using Paraview 5.12.1 and I think AMReX/BoxLib Grid Reader was causing error, I have used Paraview 5.10.1 and able to plot files. [https://amrex-codes.github.io/amrex/docs_html/Visualization.html#paraview](url) is very helpful, need to explore this more.
